# https://taskfile.dev

version: '3'

vars:
  _name_: maven.tasks.yml
  MVN_EXE: |-
    $(which mvn 2>/dev/null || echo __tools__/apache-maven-3.8.1/bin/mvn)

tasks:
  default:
    cmds:
      - echo "{{._name_}}"
      - task -l
    silent: true

  info:
    desc: _
    cmds:
      - echo "{{.MVN_EXE}}"



  # ## Resolver Of Tooling
  #
  # >
  resolve-tooling:
  #
  # ```yaml
    desc: update required tooling on system
    cmds:
    - task: _fetch-maven-arch
    - task: _unpack-maven-arch
    - task: _clean-maven-install
  # ```

  _fetch-maven-arch:
    _desc: fetches maven
    dir: __tools__
    cmds:
      - wget https://downloads.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
    status:
      - test -e apache-maven-3.8.1-bin.tar.gz

  _unpack-maven-arch:
    _desc: fetches maven
    dir: __tools__
    cmds:
      - tar -xvf apache-maven-3.8.1-bin.tar.gz
    status:
      - test -e apache-maven-3.8.1

  _clean-maven-install:
    _desc: cleanup installation files
    dir: __tools__
    cmds:
      - rm -rf aapache-maven-3.8.1-bin.tar.gz


  # ## Resolver Of Tooling
  #
  # >
  build-maven:
    desc: build maven package
    cmds:
    - |-
      {{.MVN_EXE}} compile -f pom.xml

  test-maven:
    desc: _
    cmds:
    - |-
      {{.MVN_EXE}} test -f pom.xml

  publish-maven:
    desc: _
    cmds:
    - |-
      {{.MVN_EXE}} deploy -f pom.xml

  ci-flow:
    desc: Run Full Ci Flow for maven app
    cmds:
      - task: resolve-tooling
      - task: build-maven
      - task: test-maven
      - task: publish-maven
